git rm CONTRIBUTING.md
git rm CUSTOMIZE.md
git rm Dockerfile
git rm FAQ.md
git add Gemfile
git rm INSTALL.md
git add LICENSE
git rm README.md
git add _config.yml
git rm _data/cv.yml
git rm _data/venues.yml
git rm _includes/audio.liquid
git rm _includes/cv/list.liquid
git rm _includes/cv/list_groups.liquid
git rm _includes/cv/map.liquid
git rm _includes/cv/nested_list.liquid
git rm _includes/cv/time_table.liquid
git rm _includes/disqus.liquid
git rm _includes/figure.liquid
git rm _includes/footer.liquid
git rm _includes/giscus.liquid
git rm _includes/head.liquid
git rm _includes/header.liquid
git rm _includes/latest_posts.liquid
git rm _includes/metadata.liquid
git rm _includes/news.liquid
git rm _includes/pagination.liquid
git rm _includes/projects.liquid
git rm _includes/projects_horizontal.liquid
git rm _includes/related_posts.liquid
git rm _includes/repository/repo.liquid
git rm _includes/repository/repo_trophies.liquid
git rm _includes/repository/repo_user.liquid
git rm _includes/resume/awards.liquid
git rm _includes/resume/basics.liquid
git rm _includes/resume/certificates.liquid
git rm _includes/resume/education.liquid
git rm _includes/resume/interests.liquid
git rm _includes/resume/languages.liquid
git rm _includes/resume/projects.liquid
git rm _includes/resume/publications.liquid
git rm _includes/resume/references.liquid
git rm _includes/resume/skills.liquid
git rm _includes/resume/volunteer.liquid
git rm _includes/resume/work.liquid
git rm _includes/scripts/analytics.liquid
git rm _includes/scripts/badges.liquid
git rm _includes/scripts/bootstrap.liquid
git rm _includes/scripts/chartjs.liquid
git rm _includes/scripts/diff2html.liquid
git rm _includes/scripts/echarts.liquid
git rm _includes/scripts/imageLayouts.liquid
git rm _includes/scripts/jquery.liquid
git rm _includes/scripts/leaflet.liquid
git rm _includes/scripts/masonry.liquid
git rm _includes/scripts/mathjax.liquid
git rm _includes/scripts/mermaid.liquid
git rm _includes/scripts/misc.liquid
git rm _includes/scripts/progressBar.liquid
git rm _includes/scripts/tikzjax.liquid
git rm _includes/scripts/vega.liquid
git rm _includes/scripts/wechatModal.liquid
git rm _includes/selected_papers.liquid
git rm _includes/social.liquid
git rm _includes/video.liquid
git rm _layouts/about.liquid
git rm _layouts/archive-category.liquid
git rm _layouts/archive-tag.liquid
git rm _layouts/archive-year.liquid
git rm _layouts/bib.liquid
git rm _layouts/cv.liquid
git rm _layouts/default.liquid
git rm _layouts/distill.liquid
git rm _layouts/none.liquid
git rm _layouts/page.liquid
git rm _layouts/post.liquid
git rm _layouts/profiles.liquid
git rm _news/2024_02_11.md
git rm _news/_templates/announcement_1.md
git rm _news/_templates/announcement_2.md
git rm _news/_templates/announcement_3.md
git rm _pages/404.md
git rm _pages/_templates/about_einstein.md
git rm _pages/_templates/blog.md
git rm _pages/_templates/cv.md
git rm _pages/_templates/dropdown.md
git rm _pages/_templates/news.md
git rm _pages/_templates/profiles.md
git rm _pages/_templates/publications.md
git rm _pages/_templates/repositories.md
git rm _pages/_templates/teaching.md
git add _pages/about.md
git add _pages/projects.md
git rm _plugins/cache-bust.rb
git rm _plugins/details.rb
git rm _plugins/external-posts.rb
git rm _plugins/file-exists.rb
git rm _plugins/google-scholar-citations.rb
git rm _plugins/hideCustomBibtex.rb
git rm _plugins/remove-accents.rb
git rm _posts/_templates/2015-03-15-formatting-and-links.md
git rm _posts/_templates/2015-05-15-images.md
git rm _posts/_templates/2015-07-15-code.md
git rm _posts/_templates/2015-10-20-disqus-comments.md
git rm _posts/_templates/2015-10-20-math.md
git rm _posts/_templates/2018-12-22-distill.md
git rm _posts/_templates/2020-09-28-github-metadata.md
git rm _posts/_templates/2020-09-28-twitter.md
git rm _posts/_templates/2021-07-04-diagrams.md
git rm _posts/_templates/2022-02-01-redirect.md
git rm _posts/_templates/2022-12-10-giscus-comments.md
git rm _posts/_templates/2023-03-20-table-of-contents.md
git rm _posts/_templates/2023-03-21-tables.md
git rm _posts/_templates/2023-04-24-videos.md
git rm _posts/_templates/2023-04-25-audios.md
git rm _posts/_templates/2023-04-25-sidebar-table-of-contents.md
git rm _posts/_templates/2023-05-12-custom-blockquotes.md
git rm _posts/_templates/2023-07-04-jupyter-notebook.md
git rm _posts/_templates/2023-07-12-post-bibliography.md
git rm _posts/_templates/2023-12-12-tikzjax.md
git rm _posts/_templates/2024-01-26-chartjs.md
git rm _posts/_templates/2024-01-26-echarts.md
git rm _posts/_templates/2024-01-26-geojson-map.md
git rm _posts/_templates/2024-01-27-advanced-images.md
git rm _posts/_templates/2024-01-27-code-diff.md
git rm _posts/_templates/2024-01-27-vega-lite.md
git rm _projects/2023_05_03_univers_a_lecran.md
git rm _projects/_templates/1_project.md
git rm _projects/_templates/2_project.md
git rm _projects/_templates/3_project.md
git rm _projects/_templates/4_project.md
git rm _projects/_templates/5_project.md
git rm _projects/_templates/6_project.md
git add _sass/_base.scss
git rm _sass/_cv.scss
git rm _sass/_distill.scss
git rm _sass/_layout.scss
git rm _sass/_themes.scss
git add _sass/_variables.scss
git rm _sass/font-awesome/_animated.scss
git rm _sass/font-awesome/_bordered-pulled.scss
git rm _sass/font-awesome/_core.scss
git rm _sass/font-awesome/_fixed-width.scss
git rm _sass/font-awesome/_functions.scss
git rm _sass/font-awesome/_icons.scss
git rm _sass/font-awesome/_list.scss
git rm _sass/font-awesome/_mixins.scss
git rm _sass/font-awesome/_rotated-flipped.scss
git rm _sass/font-awesome/_screen-reader.scss
git rm _sass/font-awesome/_shims.scss
git rm _sass/font-awesome/_sizing.scss
git rm _sass/font-awesome/_stacked.scss
git rm _sass/font-awesome/_variables.scss
git rm _sass/font-awesome/brands.scss
git rm _sass/font-awesome/fontawesome.scss
git rm _sass/font-awesome/regular.scss
git rm _sass/font-awesome/solid.scss
git rm _sass/font-awesome/v4-shims.scss
git rm assets/audio/epicaly-short-113909.mp3
git rm assets/bibliography/2018-12-22-distill.bib
git add assets/css/academicons.min.css
git rm assets/css/bootstrap-toc.min.css
git rm assets/css/bootstrap.min.css
git rm assets/css/bootstrap.min.css.map
git rm assets/css/jekyll-pygments-themes-github.css
git rm assets/css/jekyll-pygments-themes-native.css
git rm assets/css/jupyter-grade3.css
git rm assets/css/jupyter-monokai.css
git rm assets/css/jupyter.css
git add assets/css/main.scss
git rm assets/css/mdb.min.css
git rm assets/css/mdb.min.css.map
git add assets/fonts/academicons.ttf
git add assets/fonts/academicons.woff
git add assets/img/3.jpg
git add assets/img/4.jpg
git add assets/img/5.jpg
git add assets/img/6.jpg
git add assets/img/7.jpg
git add assets/img/8.jpg
git add assets/img/9.jpg
git rm assets/img/pagespeed.svg
git rm assets/img/prof_pic_color.png
git rm assets/img/publication_preview/brownian-motion.gif
git rm assets/img/publication_preview/wave-mechanics.gif
git rm assets/img/readme_preview/al-folio-preview.png
git rm assets/img/readme_preview/blog.png
git rm assets/img/readme_preview/code.png
git rm assets/img/readme_preview/cv.png
git rm assets/img/readme_preview/dark.png
git rm assets/img/readme_preview/distill.png
git rm assets/img/readme_preview/jupyter.png
git rm assets/img/readme_preview/light.png
git rm assets/img/readme_preview/math.png
git rm assets/img/readme_preview/people.png
git rm assets/img/readme_preview/photos-screenshot.png
git rm assets/img/readme_preview/projects.png
git rm assets/img/readme_preview/publications.png
git rm assets/img/readme_preview/repositories.png
git rm assets/js/bootstrap-toc.min.js
git rm assets/js/bootstrap.bundle.min.js
git rm assets/js/bootstrap.bundle.min.js.map
git add assets/js/common.js
git rm assets/js/copy_code.js
git rm assets/js/distillpub/overrides.js
git rm assets/js/distillpub/template.v2.js
git rm assets/js/distillpub/template.v2.js.map
git rm assets/js/distillpub/transforms.v2.js
git rm assets/js/distillpub/transforms.v2.js.map
git rm assets/js/masonry.js
git rm assets/js/mdb.min.js
git rm assets/js/mdb.min.js.map
git rm assets/js/no_defer.js
git rm assets/js/theme.js
git rm assets/js/zoom.js
git rm assets/json/resume.json
git rm assets/json/table_data.json
git rm assets/jupyter/blog.ipynb
git rm assets/pdf/example_pdf.pdf
git rm assets/plotly/demo.html
git rm assets/video/pexels-engin-akyurt-6069112-960x540-30fps.mp4
git rm assets/webfonts/fa-brands-400.ttf
git rm assets/webfonts/fa-brands-400.woff2
git rm assets/webfonts/fa-regular-400.ttf
git rm assets/webfonts/fa-regular-400.woff2
git rm assets/webfonts/fa-solid-900.ttf
git rm assets/webfonts/fa-solid-900.woff2
git rm assets/webfonts/fa-v4compatibility.ttf
git rm assets/webfonts/fa-v4compatibility.woff2
git rm bin/cibuild
git add bin/deploy
git rm bin/entry_point.sh
git rm docker-compose-slim.yml
git rm docker-compose.yml
git rm lighthouse_results/desktop/alshedivat_github_io_al_folio_.html
git rm lighthouse_results/desktop/pagespeed.svg
git rm lighthouse_results/mobile/alshedivat_github_io_al_folio_.html
git rm lighthouse_results/mobile/pagespeed.svg
git rm package-lock.json
git rm package.json
git rm purgecss.config.js
git rm reports/psresultdesktop.svg
git rm reports/psresultmobile.svg
git rm robots.txt

git add _includes/_links_library.md
git add _includes/footer.html
git add _includes/head.html
git add _includes/header.html
git add _includes/hemline.html
git add _includes/news.html
git add _includes/pagination.html
git add _includes/social.html
git add _layouts/about.html
git add _layouts/bib.html
git add _layouts/cv.html
git add _layouts/default.html
git add _layouts/none.html
git add _layouts/page.html
git add _layouts/post.html
git add _news/announcement_1.md
git add _projects/10_project.markdown
git add _projects/1_project.markdown
git add _projects/2_project.markdown
git add _projects/3_project.markdown
git add _projects/4_project.markdown
git add _projects/5_project.markdown
git add _projects/6_project.markdown
git add _projects/7_project.markdown
git add _projects/8_project.markdown
git add _projects/9_project.markdown
git add _sass/_basscss.scss
git add _sass/_blockquotes.scss
git add _sass/_clearfix.scss
git add _sass/_code.scss
git add _sass/_footer.scss
git add _sass/_gallery.scss
git add _sass/_gists.scss
git add _sass/_header.scss
git add _sass/_links.scss
git add _sass/_measure.scss
git add _sass/_media-queries.scss
git add _sass/_mixins.scss
git add _sass/_notices.scss
git add _sass/_pages.scss
git add _sass/_pagination.scss
git add _sass/_positions.scss
git add _sass/_posts.scss
git add _sass/_profile.scss
git add _sass/_projects.scss
git add _sass/_publications.scss
git add _sass/_social-icons.scss
git add _sass/_syntax-highlighting.scss
git add _sass/_tables.scss
git add _sass/_typography.scss
git add _sass/basscss/
git add _teaching/
git add assets/css/font-awesome.min.css
git add assets/css/main.css
git add assets/fonts/FontAwesome.otf
git add assets/fonts/academicons.eot
git add assets/fonts/academicons.svg
git add assets/fonts/fontawesome-webfont.eot
git add assets/fonts/fontawesome-webfont.svg
git add assets/fonts/fontawesome-webfont.ttf
git add assets/fonts/fontawesome-webfont.woff
git add assets/fonts/fontawesome-webfont.woff2
git add assets/img/CNN.png
git add assets/img/LVold.png
git add assets/img/LVs.png
git add assets/img/MPA.png
git add assets/img/XYOverTime.png
git add assets/img/code-screenshot.png
git add assets/img/dnb.jpg
git add assets/img/favicon.ico
git add assets/img/favicon_old.ico
git add assets/img/full-screenshot.png
git add assets/img/model_weights.png
git add assets/img/nais_smooth.jpg
git add assets/img/newpic.jpg
git add assets/img/pcp.jpg
git add assets/img/photos-screenshot.png
git add assets/img/qermit.jpg
git add assets/img/so-simple-sample-image-3.jpg
git add assets/img/sv_hmm.jpg
git add assets/img/why.jpg
git add assets/js/katex.js
git add blog/
git add cv/
git add git.sh
git add news/
git add research/
git add teaching/
